export default {
    "points_setup": {
        "price": 1,
        "points": 1,
        "min_order": null,
        "bonus_status": 1,
        "purchase_status": 1,
        "bonus": null,
        "welcome_bonus": 100,
        "welcome_title": null,
        "app_lang": "en_US",
        "purchase_redeem": 1,
        "purchase_theme_status": 1,
        "redeem_purchase_status": 1,
        "redeem_theme_status": 1,
        "redeem_point_per_dollar": "100",
        "login_url": "http://maverickmav.org/khaled/my-account/",
        "register_url": "http://maverickmav.org/khaled/my-account/",
        "terms_url": "http://maverickmav.org/khaled",
        "currency": "£",
        "wpversion": "3.7.7",
        "id_shop": "1302",
        "id_site": "3773",
        "plugin_type": "WP",
        "is_points_percentage": "0",
        "points_percentage": "100",
        "tax_included_product": 0,
        "tax_included_shipping": 0,
        "continue_shop_url": ""
    },
    "referral": {
        "referrer_purchase": 0,
        "goal": 1,
        "max_reward": 0,
        "reward_type": "unique",
        "referrer_reward_types": "points",
        "referral_fresh_install": 1,
        "referral_coupon_desc": "Share this coupon to give your friends an awesome offer! You’ll earn rewards when they make a purchase.",
        "referral_desc": "Invite your friends (Psst! We’ll also give you an offer to share) and get rewards when they make a purchase!",
        "referrer_reward_points": 200,
        "status": 1,
        "referrer_onesided": 0,
        "is_new": 1,
        "realtime_coupon_on_friend": 1,
        "common_referrer_reward": "",
        "realtime_coupon_type_friend": 1,
        "realtime_coupon_value_friend": 10,
        "realtime_min_order_friend": 0,
        "realtime_coupon_type": 1,
        "is_referral_completed": 1,
        "realtime_coupon_value": 10,
        "realtime_min_order": 0,
        "is_rwd_points_percentage": "0",
        "rwd_points_percentage": "10"
    },
    "entries": {
        "facebook_share": {
            "type": "facebook_share",
            "id_entry": "11342",
            "id_site": "3773",
            "id_competition": "3090",
            "title": "Share on Facebook",
            "worth_entries": "50",
            "is_mandatory": "1",
            "is_daily_entry": "1",
            "is_notify": "1",
            "form_fields": null,
            "settings": {
                "mode_points": 1,
                "mode_instant": 0,
                "instant_reward": null,
                "instant_reward_opt": null,
                "instant_reward_cpn": null,
                "instant_reward_lnk": null,
                "share_img": null,
                "share_title": "Check out this website. They are amazing!",
                "share_caption": "WP",
                "share_desc": "You have to check out this website. They have amazing products &amp; service!",
                "landing_url": "http://maverickmav.org/khaled"
            },
            "order_by": "1",
            "status": "1"
        },
        "twitter_tweet": {
            "type": "twitter_tweet",
            "id_entry": "11343",
            "id_site": "3773",
            "id_competition": "3090",
            "title": "Share on Twitter",
            "worth_entries": "50",
            "is_mandatory": "1",
            "is_daily_entry": "1",
            "is_notify": "1",
            "form_fields": null,
            "settings": {
                "mode_points": 1,
                "mode_instant": 0,
                "instant_reward": null,
                "instant_reward_opt": null,
                "instant_reward_cpn": null,
                "instant_reward_lnk": null,
                "tweet": "Check out this website. They have amazing products &amp; service! http://maverickmav.org/khaled"
            },
            "order_by": "2",
            "status": "1"
        },
        "newsletter_subscription": {
            "type": "newsletter_subscription",
            "id_entry": null,
            "id_site": "3773",
            "id_competition": "3090",
            "title": "Subscribe to our mailing list",
            "worth_entries": "1",
            "is_mandatory": "0",
            "is_daily_entry": "0",
            "is_notify": "0",
            "form_fields": null,
            "settings": {
                "title": "Subscribe to our mailing list",
                "esp_id": "",
                "esp_list_id": "",
                "esp_list_name": "",
                "subscription_note": "",
                "platform_marketing_permission": "0",
                "enable_double_optin": "0",
                "show_gdpr_msg": "0",
                "mode_points": "1",
                "mode_instant": "0",
                "instant_reward": "",
                "instant_reward_opt": "1",
                "instant_reward_text": "",
                "instant_reward_cpn": "",
                "instant_reward_lnk": "",
                "reward_type": "1",
                "realtime_coupon_type": "1",
                "realtime_coupon_value": "10",
                "realtime_min_order": 0,
                "currency": "դր.",
                "worth_entries": "1",
                "mode_query": 0
            },
            "order_by": "1",
            "status": "1"
        }
    },
    "events": {
        "member_birthday": {
            "id_reminder": null,
            "name": "Enter your birthday",
            "description": "",
            "reward_description": "",
            "is_year_required": "0",
            "reminder_type": "member_birthday",
            "other_reminder_type": null,
            "has_points": "1",
            "nb_points": "100",
            "ob_points": "100",
            "has_coupon": "0",
            "min_purchase": null,
            "min_purchase_days": null,
            "coupon_redem_instruction": null,
            "status": "1"
        }
    },
    "reviews": {
        "woo_reviews": {
            "id_entry": null,
            "id_competition": "3090",
            "review_status": "1",
            "points": "10",
            "settings": {
                "max_per_product": "1",
                "max_per_day": "10",
                "review_label_status": 1,
                "review_label": "Earn 10 points by reviewing this product.",
                "earn_point_status": [
                    "approved",
                    "unapproved"
                ],
                "subtract_point_status": [
                    "spam",
                    "trash"
                ],
                "subtract_point_period": "30",
                "wp_review_status": 1
            },
            "is_approved_only": 1
        }
    }
}